config/routes.rb
Assassin::Application.routes.draw do

  resources :kills

  resources :obituaries
  

end

app/models/kill.rb
class Kill < ActiveRecord::Base
  image_accessor :photo
  has_one :obituary

  def attack_sequence=(val)
    write_attribute(:attack_sequence, val.upcase)
  end

  def kill_date
  	read_attribute(:kill_date) || self.created_at
  end
end

app/controllers/kills_controller.rb
class KillsController < ApplicationController
  protect_from_forgery :except => :create

  # GET /kills
  # GET /kills.xml
  def index
    @kills = Kill.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @kills }
    end
  end

  # GET /kills/1
  # GET /kills/1.xml
  def show
    @kill = Kill.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @kill }
    end
  end

  # GET /kills/new
  # GET /kills/new.xml
  def new
    @kill = Kill.new

    @kill.killer_id = "583002418"
    @kill.victim_id = "867800458"

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @kill }
    end
  end

  # GET /kills/1/edit
  def edit
    @kill = Kill.find(params[:id])
  end

  # POST /kills
  # POST /kills.xml
  def create
    if params[:kill]
      @kill = Kill.new(params[:kill])
    else
      @kill = Kill.new(
        :killer_id => params[:killer_id], 
        :victim_id => params[:victim_id], 
        :location => params[:location], 
        :attack_sequence => params[:attack_sequence], 
        :photo => params[:photo],
        :kill_date => params[:kill_date]
      )
    end

    @access_token = params[:access_token]
    
    @assassin = get_facebook_data(@kill.killer_id, nil, @access_token)
    @victim = get_facebook_data(@kill.victim_id, nil, @access_token)
    
    begin
      @friends = get_facebook_data(@kill.victim_id, 'friends', @access_token)
      @fb_friends_count = @friends["data"].length
    rescue
      @fb_friends_count = nil
    end
    
    @body = get_facebook_data(@kill.victim_id, 'movies', @access_token)
    if (@body["data"][0] == nil)
      @favorite_movie = nil
    else
      @favorite_movie = @body["data"][0]["name"]
    end
    
    @body = get_facebook_data(@kill.victim_id, 'music', @access_token)
    if (@body["data"][0] == nil)
      @favorite_band = nil
    else
      @favorite_band = @body["data"][0]["name"]
    end
    
    @body = get_facebook_data(@kill.victim_id, 'books', @access_token)
    if (@body["data"][0] == nil)
      @favorite_book = nil
    else
      @favorite_book = @body["data"][0]["name"]
    end
    
    @body = get_facebook_data(@kill.victim_id, 'events', @access_token)
    if (@body["data"][0] == nil)
      @recent_event = nil
    else
      @recent_event = @body["data"][0]["name"]
    end
    
    @body = get_facebook_data(@kill.victim_id, 'feed', @access_token)
    if @body
      for i in 0...@body["data"].length
        if ((@body["data"][i]["to"] == nil) && (@body["data"][i]["message"] != nil) && (@body["data"][i]["from"]["name"] == (@victim["first_name"] + " " + @victim["last_name"])))
          @last_status_update = @body["data"][i]["message"]
          break
        end
      end
    else
      @last_status_update = nil
    end
    
    # Location
    begin
      @locations_list = get_locations(@kill.location, @access_token)
    rescue
      @locations_list = nil
    end
    
    if (@locations_list.nil? || @locations_list["data"].length.zero?)
      @location = "the scene of the crime"
    else
      @location = @locations_list["data"][0]["name"]
    end
    
    @assassin_photo = RestClient.get("https://graph.facebook.com/#{@kill.killer_id}/picture", :params => {
      :type => :large,
      :access_token => @access_token
    }).body
    
    @kill.create_obituary(
      :first_name => @victim["first_name"],
      :last_name => @victim["last_name"],
      :assassin_full_name => @assassin["name"],
      :assassin_photo => @assassin_photo,
      :gender => @victim["gender"],
      :fb_friends_count => @fb_friends_count,
      :favorite_movie => @favorite_movie,
      :favorite_band => @favorite_band,
      :favorite_book => @favorite_book,
      :recent_event => @recent_event,
      :last_status_update => @last_status_update,
      :location => @location
    )
    
    if @kill.save
      render :text => obituary_url(@kill.obituary)
    else
      render :text => @kill.errors.inspect
    end
  end

  # PUT /kills/1
  # PUT /kills/1.xml
  def update
    @kill = Kill.find(params[:id])

    respond_to do |format|
      if @kill.update_attributes(params[:kill])
        format.html { redirect_to(@kill, :notice => 'Kill was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @kill.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /kills/1
  # DELETE /kills/1.xml
  def destroy
    @kill = Kill.find(params[:id])
    @kill.destroy

    respond_to do |format|
      format.html { redirect_to(kills_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/kills_helper.rb
module KillsHelper
end

app/views/kills/_form.html.erb
<%= form_for(@kill, :html => {:multipart => true}) do |f| %>
  <% if @kill.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@kill.errors.count, "error") %> prohibited this kill from being saved:</h2>

      <ul>
      <% @kill.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  

  <div class="field">
    <%= f.label :killer_id %><br />
    <%= f.text_field :killer_id %>
  </div>
  <div class="field">
    <%= f.label :victim_id %><br />
    <%= f.text_field :victim_id %>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :kill_date %><br />
    <%= f.text_field :kill_date %>
  </div>

  <div class="field">
    <%= f.label :photo %><br />
    <%= f.file_field :photo %>
  </div>
  <div class="field">
    <%= f.label :attack_sequence %><br />
    <%= f.text_field :attack_sequence %>
  </div>
  <input type='text' name='access_token' value="2227470867|2.J7z6gIO0_jiSwr5RS0Iedw__.3600.1298862000-583002418|_Hy_HsMswuC1e9yt6aXFUW2DYYo"/>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/kills/edit.html.erb
<h1>Editing kill</h1>

<%= render 'form' %>

<%= link_to 'Show', @kill %> |
<%= link_to 'Back', kills_path %>

app/views/kills/index.html.erb
<h1>Listing kills</h1>

<table>
  <tr>
    <th>Killer</th>
    <th>Victim</th>
    <th>Location</th>
    <th>Photo uid</th>
    <th>Attack sequence</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @kills.each do |kill| %>
  <tr>
    <td><%= kill.killer_id %></td>
    <td><%= kill.victim_id %></td>
    <td><%= kill.location %></td>
    <td><%= kill.photo_uid %></td>
    <td><%= kill.attack_sequence %></td>
    <td><%= link_to 'Show', kill %></td>
    <td><%= link_to 'Edit', edit_kill_path(kill) %></td>
    <td><%= link_to 'Destroy', kill, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Kill', new_kill_path %>

app/views/kills/new.haml
%h1 New kill

= render 'form'

= link_to 'Back', kills_path

app/views/kills/show.haml
%p#notice=notice

%p
  %b Killer:
  = @kill.killer_id

%p
  %b Victim:
  = @kill.victim_id

%p
  %b Location:
  = @kill.location 

%p
  %b Photo:
  -if @kill.photo
    %img{:src => @kill.photo.url} 

%p
  %b Attack sequence:
  = @kill.attack_sequence


= link_to 'Edit', edit_kill_path(@kill) 
|
= link_to 'Back', kills_path